sudu: required
services:
    - docker
before_install:
    - docker build -t phamanhtuan221995/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run phamanhtuan221995/react-test npm test -- --coverage

after_success: 
    - docker build -t phamanhtuan221995/multi-client ./client
    - docker build -t phamanhtuan221995/multi-nginx ./nginx
    - docker build -t phamanhtuan221995/multi-server ./server
    - docker build -t phamanhtuan221995/multi-worker ./worker
    #Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take the images and push to docker hub
    - docker push phamanhtuan221995/multi-client
    - docker push phamanhtuan221995/multi-nginx
    - docker push phamanhtuan221995/multi-server
    - docker push phamanhtuan221995/multi-worker

